<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Ticket;
use App\Models\User;
use App\Models\Department;
use Carbon\Carbon;

class TicketSeeder extends Seeder
{
    public function run(): void
    {
        $employees = User::where('role', 'employee')->get()->keyBy(fn($u) => $u->email);
        $admins    = User::where('role', 'admin')->get();
        $adminIT   = $admins->firstWhere('email', 'admin@helpdesk.com');
        $adminHR   = $admins->firstWhere('email', 'hradmin@helpdesk.com');

        $dept = fn($name) => Department::where('name', $name)->first()->id;

        $itDept      = $dept('Information Technology');
        $hrDept      = $dept('Human Resources');
        $financeDept = $dept('Finance');
        $opsDept     = $dept('Operations');
        $mktDept     = $dept('Marketing');
        $legalDept   = $dept('Legal');

        $daysAgo = fn(int $min, int $max) => Carbon::now()->subDays(rand($min, $max));

        $tickets = [

            // ── INFORMATION TECHNOLOGY ──────────────────────────────────────

            ['title' => 'Cannot login to company email',             'description' => 'User unable to login to company email since Monday morning. Password reset was attempted but still fails with "Invalid credentials" error.',                                          'status' => 'open',        'priority' => 'high',   'department_id' => $itDept,      'user_id' => $employees['rahul@example.com']->id,  'assigned_to' => null,          'created_at' => $daysAgo(1, 3)],
            ['title' => 'Laptop running extremely slow',             'description' => 'Laptop takes over 10 minutes to boot. Multiple apps crash on startup. RAM usage hits 95% even with no applications open.',                                                           'status' => 'in_progress', 'priority' => 'medium', 'department_id' => $itDept,      'user_id' => $employees['priya@example.com']->id,  'assigned_to' => $adminIT->id,  'created_at' => $daysAgo(4, 7)],
            ['title' => 'Adobe Acrobat Pro installation required',   'description' => 'Need Adobe Acrobat Pro installed on workstation WIN-AMIT-01 for document signing workflows. Approval from manager already obtained.',                                                'status' => 'closed',      'priority' => 'low',    'department_id' => $itDept,      'user_id' => $employees['amit@example.com']->id,   'assigned_to' => $adminIT->id,  'created_at' => $daysAgo(20, 30)],
            ['title' => '3rd floor printer not responding',          'description' => 'HP LaserJet on 3rd floor not responding to print jobs from any workstation. Paper jam light is not showing; it simply sits idle.',                                                   'status' => 'open',        'priority' => 'medium', 'department_id' => $itDept,      'user_id' => $employees['rahul@example.com']->id,  'assigned_to' => null,          'created_at' => $daysAgo(1, 2)],
            ['title' => 'VPN connection fails from home',            'description' => 'Unable to connect to office VPN from home network. Error: "Authentication failed – certificate mismatch". Worked fine until last Thursday.',                                         'status' => 'in_progress', 'priority' => 'high',   'department_id' => $itDept,      'user_id' => $employees['priya@example.com']->id,  'assigned_to' => $adminIT->id,  'created_at' => $daysAgo(3, 5)],
            ['title' => 'Internet drops every 30 minutes',           'description' => 'Office internet on 2nd floor disconnects every 30 minutes and takes 2-3 minutes to restore. Affects all users on that floor.',                                                      'status' => 'open',        'priority' => 'high',   'department_id' => $itDept,      'user_id' => $employees['amit@example.com']->id,   'assigned_to' => null,          'created_at' => $daysAgo(1, 2)],
            ['title' => 'Monitor flickering causing eye strain',     'description' => 'Dell monitor model D2421H flickers every few minutes. IT asset tag: AST-2241. Issue started after recent Windows update.',                                                          'status' => 'closed',      'priority' => 'low',    'department_id' => $itDept,      'user_id' => $employees['rahul@example.com']->id,  'assigned_to' => $adminIT->id,  'created_at' => $daysAgo(25, 35)],
            ['title' => 'Zoom crashes on joining meetings',          'description' => 'Zoom application crashes immediately when joining any meeting. Reinstallation was attempted twice. Version: 5.16.2. OS: Windows 11.',                                                'status' => 'in_progress', 'priority' => 'high',   'department_id' => $itDept,      'user_id' => $employees['priya@example.com']->id,  'assigned_to' => $adminIT->id,  'created_at' => $daysAgo(2, 4)],
            ['title' => 'Antivirus definitions outdated',            'description' => 'Kaspersky antivirus showing definitions are 14 days out of date. Auto-update is enabled but failing silently.',                                                                      'status' => 'open',        'priority' => 'low',    'department_id' => $itDept,      'user_id' => $employees['amit@example.com']->id,   'assigned_to' => null,          'created_at' => $daysAgo(5, 8)],
            ['title' => 'Database connection timeout in ERP',        'description' => 'Internal ERP application shows DB connection timeout every 45-60 minutes. Requires manual restart of the app to resume work.',                                                       'status' => 'in_progress', 'priority' => 'high',   'department_id' => $itDept,      'user_id' => $employees['rahul@example.com']->id,  'assigned_to' => $adminIT->id,  'created_at' => $daysAgo(6, 10)],
            ['title' => 'Shared drive folder permissions incorrect', 'description' => 'Finance team cannot access the Q2 Budget folder on shared drive despite being part of the Finance-RW security group.',                                                              'status' => 'open',        'priority' => 'medium', 'department_id' => $itDept,      'user_id' => $employees['priya@example.com']->id,  'assigned_to' => null,          'created_at' => $daysAgo(1, 3)],
            ['title' => 'New employee laptop setup – Riya Kapoor',   'description' => 'New employee Riya Kapoor joins on Monday. Needs laptop configured with standard software stack, domain join, and email account.',                                                    'status' => 'open',        'priority' => 'high',   'department_id' => $itDept,      'user_id' => $employees['amit@example.com']->id,   'assigned_to' => null,          'created_at' => $daysAgo(0, 1)],
            ['title' => 'Microsoft Teams audio not working',         'description' => 'No audio input or output in Microsoft Teams. Other apps like Zoom and YouTube work fine. Issue started after Windows audio driver update.',                                          'status' => 'closed',      'priority' => 'medium', 'department_id' => $itDept,      'user_id' => $employees['rahul@example.com']->id,  'assigned_to' => $adminIT->id,  'created_at' => $daysAgo(40, 55)],
            ['title' => 'Two-factor authentication not working',     'description' => 'OTP for 2FA login not being received on registered mobile number. Checked spam folder. Issue affects login to HR portal and ERP.',                                                   'status' => 'open',        'priority' => 'high',   'department_id' => $itDept,      'user_id' => $employees['priya@example.com']->id,  'assigned_to' => null,          'created_at' => $daysAgo(0, 1)],

            // ── HUMAN RESOURCES ─────────────────────────────────────────────

            ['title' => 'New joiner account and access setup',       'description' => 'New employee Karan Mehta joins on Monday as a Finance Analyst. Requires email account, ERP access, and ID card request.',                                                           'status' => 'open',        'priority' => 'medium', 'department_id' => $hrDept,      'user_id' => $employees['sneha@example.com']->id,  'assigned_to' => null,          'created_at' => $daysAgo(1, 2)],
            ['title' => 'Leave carry-forward policy clarification',  'description' => 'Multiple employees asking about carry-forward limit for unused PL from 2025. HR portal shows conflicting information vs the policy PDF.',                                            'status' => 'closed',      'priority' => 'low',    'department_id' => $hrDept,      'user_id' => $employees['vikram@example.com']->id, 'assigned_to' => $adminHR->id,  'created_at' => $daysAgo(30, 45)],
            ['title' => 'Offer letter not received by candidate',    'description' => 'Candidate Rohit Agarwal (selected on 5th June) has not received his offer letter. Joining date is next week. Urgent follow-up needed.',                                             'status' => 'in_progress', 'priority' => 'high',   'department_id' => $hrDept,      'user_id' => $employees['neha@example.com']->id,   'assigned_to' => $adminHR->id,  'created_at' => $daysAgo(3, 5)],
            ['title' => 'Biometric attendance not recording punches','description' => 'Biometric device on ground floor is not recording entry/exit for several employees. Data shows them as absent even though they are present.',                                         'status' => 'open',        'priority' => 'high',   'department_id' => $hrDept,      'user_id' => $employees['sneha@example.com']->id,  'assigned_to' => null,          'created_at' => $daysAgo(2, 4)],
            ['title' => 'May salary slip missing from portal',       'description' => 'Several employees in Operations and Marketing cannot see May 2026 salary slip in the HRMS portal. June slips are visible.',                                                          'status' => 'in_progress', 'priority' => 'high',   'department_id' => $hrDept,      'user_id' => $employees['vikram@example.com']->id, 'assigned_to' => $adminHR->id,  'created_at' => $daysAgo(4, 6)],
            ['title' => 'Medical insurance card not received',       'description' => 'Employee Neha Patel\'s corporate health insurance card not received despite enrollment 6 weeks ago. TPA reference: GHI-2026-0441.',                                                  'status' => 'open',        'priority' => 'medium', 'department_id' => $hrDept,      'user_id' => $employees['neha@example.com']->id,   'assigned_to' => null,          'created_at' => $daysAgo(5, 8)],
            ['title' => 'Performance review form not accessible',    'description' => 'Q2 performance review form is not showing in the HRMS portal for IT department employees. Deadline is this Friday.',                                                                 'status' => 'open',        'priority' => 'medium', 'department_id' => $hrDept,      'user_id' => $employees['sneha@example.com']->id,  'assigned_to' => null,          'created_at' => $daysAgo(1, 2)],
            ['title' => 'Relieving letter not issued to ex-employee','description' => 'Former employee Ananya Sharma (last working day: 31 May) has not received relieving letter and experience certificate. She has followed up thrice.',                                 'status' => 'closed',      'priority' => 'medium', 'department_id' => $hrDept,      'user_id' => $employees['vikram@example.com']->id, 'assigned_to' => $adminHR->id,  'created_at' => $daysAgo(15, 20)],

            // ── FINANCE ─────────────────────────────────────────────────────

            ['title' => 'Payroll calculation error for June',        'description' => 'Payroll software throwing arithmetic error during June 2026 run. Affects employees with LOP days. Error code: PAY-ERR-0042.',                                                       'status' => 'open',        'priority' => 'high',   'department_id' => $financeDept, 'user_id' => $employees['rohit@example.com']->id,  'assigned_to' => null,          'created_at' => $daysAgo(1, 2)],
            ['title' => 'Budget Excel file shows corrupt error',     'description' => 'FY2026_Q3_Budget.xlsx returns "File format or file extension is not valid" on every machine. File was last edited on SharePoint.',                                                   'status' => 'in_progress', 'priority' => 'high',   'department_id' => $financeDept, 'user_id' => $employees['kavita@example.com']->id, 'assigned_to' => $adminIT->id,  'created_at' => $daysAgo(3, 5)],
            ['title' => 'Travel reimbursement still pending',        'description' => 'Reimbursement claim of ₹14,200 for Bengaluru client visit (submitted 22 May) still showing as "Under Review". Manager has already approved.',                                       'status' => 'open',        'priority' => 'medium', 'department_id' => $financeDept, 'user_id' => $employees['suresh@example.com']->id, 'assigned_to' => null,          'created_at' => $daysAgo(7, 10)],
            ['title' => 'Vendor invoice stuck in approval',          'description' => 'Invoice #INV-2026-0891 from TechSupplies Pvt Ltd (₹87,500) pending approval for 12 days. Vendor is following up daily.',                                                            'status' => 'in_progress', 'priority' => 'medium', 'department_id' => $financeDept, 'user_id' => $employees['rohit@example.com']->id,  'assigned_to' => $adminHR->id,  'created_at' => $daysAgo(8, 12)],
            ['title' => 'Form 16 required for FY 2025-26',          'description' => 'Need Form 16 (Part A and Part B) for FY 2025-26 for income tax filing. Deadline for filing is 31 July 2026.',                                                                        'status' => 'closed',      'priority' => 'low',    'department_id' => $financeDept, 'user_id' => $employees['kavita@example.com']->id, 'assigned_to' => $adminHR->id,  'created_at' => $daysAgo(20, 25)],
            ['title' => 'GST portal access credentials expired',     'description' => 'Finance team needs access to GST portal for July filing. Current login credentials are expired and reset OTP is not arriving.',                                                     'status' => 'open',        'priority' => 'high',   'department_id' => $financeDept, 'user_id' => $employees['suresh@example.com']->id, 'assigned_to' => null,          'created_at' => $daysAgo(1, 3)],
            ['title' => 'Tally software license expiring soon',      'description' => 'Tally Prime license expires in 5 days. Need renewal for 3 users in Finance. Vendor contact: Shyam Agencies.',                                                                       'status' => 'in_progress', 'priority' => 'high',   'department_id' => $financeDept, 'user_id' => $employees['rohit@example.com']->id,  'assigned_to' => $adminIT->id,  'created_at' => $daysAgo(3, 4)],
            ['title' => 'Incorrect TDS deduction in April salary',   'description' => 'TDS deducted in April 2026 salary appears higher than declared investment proofs. Difference of approx ₹3,200. Request for correction.',                                            'status' => 'closed',      'priority' => 'medium', 'department_id' => $financeDept, 'user_id' => $employees['kavita@example.com']->id, 'assigned_to' => $adminHR->id,  'created_at' => $daysAgo(35, 50)],

            // ── OPERATIONS ──────────────────────────────────────────────────

            ['title' => 'Stationery and paper stock running low',    'description' => 'A4 paper stock is down to 2 reams for the entire 2nd floor. Pens, staplers, and folders also critically low. Monthly indent not raised.',                                            'status' => 'open',        'priority' => 'low',    'department_id' => $opsDept,     'user_id' => $employees['anita@example.com']->id,  'assigned_to' => null,          'created_at' => $daysAgo(2, 4)],
            ['title' => 'AC not cooling in cabin 204',               'description' => 'Split AC in cabin 204 running but not cooling. Temperature inside reaches 30°C+ by noon. AMC vendor has been informed but no response.',                                             'status' => 'in_progress', 'priority' => 'medium', 'department_id' => $opsDept,     'user_id' => $employees['deepak@example.com']->id, 'assigned_to' => $adminHR->id,  'created_at' => $daysAgo(4, 7)],
            ['title' => 'Unauthorized vehicles in parking',          'description' => 'Slots B-12 to B-15 (reserved for senior staff) regularly occupied by unregistered vehicles. Security has been informed but issue persists.',                                         'status' => 'open',        'priority' => 'low',    'department_id' => $opsDept,     'user_id' => $employees['anita@example.com']->id,  'assigned_to' => null,          'created_at' => $daysAgo(5, 9)],
            ['title' => 'Cafeteria food quality deteriorated',       'description' => 'Multiple employee complaints about food quality and hygiene in the cafeteria over the past 2 weeks. Request for management review of vendor contract.',                               'status' => 'open',        'priority' => 'medium', 'department_id' => $opsDept,     'user_id' => $employees['deepak@example.com']->id, 'assigned_to' => null,          'created_at' => $daysAgo(3, 6)],
            ['title' => 'Conference room projector not working',     'description' => 'Projector in Conference Room A shows "No Signal" despite correct cable connections. Client presentation scheduled tomorrow at 10 AM.',                                               'status' => 'in_progress', 'priority' => 'high',   'department_id' => $opsDept,     'user_id' => $employees['anita@example.com']->id,  'assigned_to' => $adminIT->id,  'created_at' => $daysAgo(0, 1)],
            ['title' => 'Water dispenser not working on 4th floor',  'description' => 'Hot & cold water dispenser on 4th floor stopped working. No hot water and cold water flow is weak. Over 40 employees affected.',                                                     'status' => 'closed',      'priority' => 'medium', 'department_id' => $opsDept,     'user_id' => $employees['deepak@example.com']->id, 'assigned_to' => $adminHR->id,  'created_at' => $daysAgo(18, 25)],
            ['title' => 'Elevator making grinding noise',            'description' => 'Elevator 1 making loud grinding noise and occasionally stops between floors. AMC inspection is due. Safety concern for all employees.',                                               'status' => 'open',        'priority' => 'high',   'department_id' => $opsDept,     'user_id' => $employees['anita@example.com']->id,  'assigned_to' => null,          'created_at' => $daysAgo(1, 2)],

            // ── MARKETING ───────────────────────────────────────────────────

            ['title' => 'Admin access needed for social media',      'description' => 'Marketing team needs admin-level access to company LinkedIn, Twitter/X, and Instagram accounts for Q3 campaign launch.',                                                             'status' => 'open',        'priority' => 'medium', 'department_id' => $mktDept,     'user_id' => $employees['pooja@example.com']->id,  'assigned_to' => null,          'created_at' => $daysAgo(2, 4)],
            ['title' => 'Canva Pro team license expired',            'description' => 'Canva Pro license for team of 5 expired on 10th June. Design work for all ongoing campaigns is blocked. Renewal invoice shared with Finance.',                                       'status' => 'in_progress', 'priority' => 'high',   'department_id' => $mktDept,     'user_id' => $employees['arjun@example.com']->id,  'assigned_to' => $adminIT->id,  'created_at' => $daysAgo(5, 7)],
            ['title' => 'Google Analytics not loading campaign data','description' => 'GA4 dashboard shows "Data processing" for last 3 days. June campaign data (est. 50K+ impressions) not visible. Other GA accounts working fine.',                                    'status' => 'open',        'priority' => 'medium', 'department_id' => $mktDept,     'user_id' => $employees['pooja@example.com']->id,  'assigned_to' => null,          'created_at' => $daysAgo(3, 5)],
            ['title' => 'HubSpot CRM not syncing with Salesforce',  'description' => 'HubSpot and Salesforce stopped syncing leads since June 8. Over 200 new leads captured on website not appearing in CRM.',                                                            'status' => 'open',        'priority' => 'high',   'department_id' => $mktDept,     'user_id' => $employees['arjun@example.com']->id,  'assigned_to' => null,          'created_at' => $daysAgo(1, 2)],
            ['title' => 'Email campaign delivery rate dropped',      'description' => 'June newsletter delivery rate dropped to 61% from usual 92%. Bounce rate spiked. Possible domain reputation issue. Mailchimp support ticket raised.',                               'status' => 'in_progress', 'priority' => 'high',   'department_id' => $mktDept,     'user_id' => $employees['pooja@example.com']->id,  'assigned_to' => $adminIT->id,  'created_at' => $daysAgo(4, 6)],
            ['title' => 'Blog publishing access on CMS',             'description' => 'New marketing executive Divya does not have Author role on WordPress CMS. Needs access to publish blog posts and upload media.',                                                     'status' => 'closed',      'priority' => 'low',    'department_id' => $mktDept,     'user_id' => $employees['arjun@example.com']->id,  'assigned_to' => $adminIT->id,  'created_at' => $daysAgo(22, 30)],

            // ── LEGAL ───────────────────────────────────────────────────────

            ['title' => 'Cannot access vendor contracts on SharePoint','description' => 'Legal team unable to access the "Vendor Contracts 2026" folder on SharePoint. Error: "Access Denied". Folder was accessible until last week.',                                   'status' => 'open',        'priority' => 'high',   'department_id' => $legalDept,   'user_id' => $employees['sunita@example.com']->id, 'assigned_to' => null,          'created_at' => $daysAgo(1, 3)],
            ['title' => 'Mandatory compliance training pending',     'description' => 'POSH and Data Privacy compliance training (mandatory annually) due by 30 June for entire organization. LMS is not sending reminder emails.',                                          'status' => 'in_progress', 'priority' => 'medium', 'department_id' => $legalDept,   'user_id' => $employees['manish@example.com']->id, 'assigned_to' => $adminHR->id,  'created_at' => $daysAgo(5, 8)],
            ['title' => 'Updated NDA template required',             'description' => 'Current NDA template (v2.1) needs updating with new data protection clauses per IT Amendment Act 2023. Required for 3 pending vendor onboardings.',                                  'status' => 'closed',      'priority' => 'low',    'department_id' => $legalDept,   'user_id' => $employees['sunita@example.com']->id, 'assigned_to' => $adminHR->id,  'created_at' => $daysAgo(28, 40)],
            ['title' => 'SaaS vendor contract review required',      'description' => 'New SaaS vendor (CloudOps Pvt Ltd) contract received. Requires legal review before signing. Contract value: ₹12L/year. Deadline: 20 June.',                                         'status' => 'open',        'priority' => 'high',   'department_id' => $legalDept,   'user_id' => $employees['manish@example.com']->id, 'assigned_to' => null,          'created_at' => $daysAgo(2, 4)],
            ['title' => 'IP ownership clause dispute with client',   'description' => 'Client ABC Corp contesting IP ownership clause in Master Services Agreement. Need to prepare revised clause with comparison of original and proposed.',                               'status' => 'in_progress', 'priority' => 'high',   'department_id' => $legalDept,   'user_id' => $employees['sunita@example.com']->id, 'assigned_to' => $adminHR->id,  'created_at' => $daysAgo(6, 9)],
            ['title' => 'Background verification reports pending',   'description' => '5 new employee BGV reports from AuthBridge still pending after 4 weeks. HR is awaiting clearance before issuing confirmation letters.',                                              'status' => 'open',        'priority' => 'medium', 'department_id' => $legalDept,   'user_id' => $employees['manish@example.com']->id, 'assigned_to' => null,          'created_at' => $daysAgo(4, 7)],
            ['title' => 'Trademark registration status check',       'description' => 'Company trademark application (TM Ref: 2024/TM/04421) filed 18 months ago. No update from IP India portal. Need to follow up with external attorney.',                              'status' => 'closed',      'priority' => 'low',    'department_id' => $legalDept,   'user_id' => $employees['sunita@example.com']->id, 'assigned_to' => $adminHR->id,  'created_at' => $daysAgo(50, 70)],
        ];

        foreach ($tickets as $ticket) {
            $createdAt = $ticket['created_at'];

            $updatedAt = $ticket['status'] === 'closed'
                ? (clone $createdAt)->addDays(rand(1, 7))
                : (clone $createdAt)->addHours(rand(1, 12));

            Ticket::create([
                'title'         => $ticket['title'],
                'description'   => $ticket['description'],
                'status'        => $ticket['status'],
                'priority'      => $ticket['priority'],
                'department_id' => $ticket['department_id'],
                'user_id'       => $ticket['user_id'],
                'assigned_to'   => $ticket['assigned_to'],
                'created_at'    => $createdAt,
                'updated_at'    => $updatedAt,
            ]);
        }
    }
}